//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sivam.web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOTPDetail
    {
        public int RecId { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Type { get; set; }
        public string APIResponse { get; set; }
        public string APIRequest { get; set; }
        public int BookingId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
